<div class="actions">
    <?php if ($_product->isSaleable()): ?>
    <?php if (Mage::getStoreConfig('ajax/general/enabledpro')){ ?>

        <?php if (!($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped())) { ?>
            <p>
                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"
                        onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId() ?>')">
                    <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
            </p>
            <span id='ajax_loader<?php echo $_product->getId() ?>' style='display:none'><img
                    src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>'/></span>
        <?php } else { ?>
            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"
                    onclick="showOptions('<?php echo $_product->getId() ?>')">
                <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
            <a href='<?php echo $this->getUrl('ajax/index/options', array('product_id' => $_product->getId())); ?>'
               class='fancybox' id='fancybox<?php echo $_product->getId() ?>' style='display:none'>Test</a>
        <?php } ?>

    <?php }else{ ?>
    <p>
        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"
                onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
            <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
    </p>


</div>


<div class="toolbar-bottom">
    <?php echo $this->getToolbarHtml() ?>
</div>
</div>
<?php endif; ?>
<script type="text/javascript">
    jQuery.noConflict();
    jQuery(document).ready(function () {
        jQuery('.fancybox').fancybox(
            {
                hideOnContentClick: true,
                width: 382,
                autoDimensions: true,
                type: 'iframe',
                showTitle: false,
                scrolling: 'no',
                onComplete: function () {
                    jQuery('#fancybox-frame').load(function () { // wait for frame to load and then gets it's height
                        jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height() + 30);
                        jQuery.fancybox.resize();
                    });

                }
            }
        );
    });
    function showOptions(id) {
        jQuery('#fancybox' + id).trigger('click');
    }
    function setAjaxData(data, iframe) {
        if (data.status == 'ERROR') {
            alert(data.message);
        } else {
            if (jQuery('.block-cart')) {
                jQuery('.block-cart').replaceWith(data.sidebar);
            }
            if (jQuery('.header .links')) {
                jQuery('.header .links').replaceWith(data.toplink);
            }
            jQuery.fancybox.close();
        }
    }
    function setLocationAjax(url, id) {
        url += 'isAjax/1';
        url = url.replace("checkout/cart", "ajax/index");
        jQuery('#ajax_loader' + id).show();
        try {
            jQuery.ajax({
                url: url,
                dataType: 'json',
                success: function (data) {
                    jQuery('#ajax_loader' + id).hide();
                    setAjaxData(data, false);
                }
            });
        } catch (e) {
        }
    }
</script>