<?php $_order = $this->getOrder() ?>
<div class="box-left">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Customer Comment') ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <?php
                $customVars = $this->getCustomVars();
                foreach($customVars as $customVar){
                    ?>
                    <tr>
                        <?php /*<td style="width:10%" class="label"><strong><?php echo Mage::helper('sales')->__($customVar['key']) ?></strong></td>*/ ?>
                        <td class="value"><?php echo nl2br($customVar['value']);?></td>
                    </tr>
                <?php } ?>
            </table>
        </div>
    </div>
</div>
<div class="clear"></div>
