<?php
$_product = $this->getProduct();
$_attributes = Mage::helper('core')->decorateArray($this->getAllowAttributes());
if (!$_product->isSaleable() || !count($_attributes)) {
    return;
}
$swatchAttributes = Mage::helper('swatchattrg')->getSwatchAttributes();
$storeId = Mage::app()->getStore()->getId();
?>
<dl>
    <?php foreach ($_attributes as $_attribute): ?>
        <?php
        $_productAttribute = $_attribute->getProductAttribute();
        $_attributeCode = $_productAttribute->getAttributeCode();
        $_attributeId = $_attribute->getAttributeId();
        $_label = $_productAttribute->getFrontendLabel();
        $title = ' - <span id="divattribute' . $_attributeId . '" class="swatchLabel">' . $this->__('Choose Option') . '</span>';
        ?>
        <?php if (in_array($_attributeCode, $swatchAttributes)): ?>
            <?php $attributeId = $_attribute->getAttributeId(); ?>
            <dd<?php if ($_attribute->decoratedIsLast) { ?> class="last <?php echo $_attributeCode; ?>"<?php } ?>>
                <label class="required"><?php echo $_label ?></label>
                <div class="input-box">
                    <select name="super_attribute[<?php echo $_attributeId ?>]" id="attribute<?php echo $_attributeId ?>" 
                            class="required-entry super-attribute-select swatchSelect">
                        <option><?php echo $this->__('Choose an Option...') ?></option>
                    </select>
                </div>
                <?php echo Mage::helper('swatchattrg')->getSwatchHtml($_attributeCode, $_attributeId, $_product); ?>
                <div style="display: none;" id="advice-required-entry-attribute<?php echo $attributeId ?>" class="validation-advice"><?php echo $this->__('This is a required field.') ?></div>
            </dd>
        <?php else: ?>
            <dd<?php if ($_attribute->decoratedIsLast) { ?> class="last <?php echo $_attributeCode; ?>"<?php } ?>>
                <label class="required"><?php echo $_label ?></label>
                <div class="input-box">
                    <select name="super_attribute[<?php echo $_attributeId; ?>]" id="attribute<?php echo $_attributeId; ?>" class="required-entry super-attribute-select">
                        <option><?php echo $this->__('Choose an Option...') ?></option>
                    </select>
                </div>
            </dd>
        <?php endif; ?>
    <?php endforeach; ?>
            
    <script type="text/javascript">
        var spConfig = new Product.Config(<?php echo $this->getJsonConfig() ?>);
        var selecttitle = '<?php echo $this->__('Choose Option'); ?>';
        var swatchJson = <?php echo $this->helper('swatchattrg')->getSwatchJson(); ?>;
        var jsonOptionProduct = <?php echo $this->getJsonOptionProduct(); ?>;
        var jsonAttribute = <?php echo $this->getJsonAttribute(); ?>;
    </script>
