<?php
$_filters = $this->getActiveFilters();
$swatchAttributes = Mage::helper('swatchattrg')->getSwatchAttributes();
$_sHelper = $this->helper('swatchattrg/model');
if (empty($_filters)) {
    return;
}
?>

<div class="currently">
    <p class="block-subtitle"><?php echo $this->__('Currently Shopping by:') ?></p>
    <ol>
        <?php foreach ($_filters as $_filter): ?>
            <?php
            $attributeCode = $_filter->getFilter()->getAttributeModel()->getData('attribute_code');
            $label = $this->stripTags($_filter->getLabel());
            ?>
            <?php
            if (in_array($attributeCode, $swatchAttributes) &&
                    $this->helper('swatchattrg/config')->getConfig('general', 'showonlayer')):
                ?>
                <?php
                $optionId = $_filter->getValueString();
                $_imageSwatch = Mage::helper('swatchattrg')->getSwatchUrl($optionId);
                if (!$_imageSwatch && $attributeCode == 'color') {
                    $_bgSwatch = strtolower($label);
                } else {
                    $_bgSwatch = false;
                }
                ?>

                <li>
                    <a href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo $this->__('Remove This Item') ?>" class="btn-remove"><?php echo $this->__('Remove This Item') ?></a>
                    <span class="label"><?php echo $this->__($_filter->getName()) ?>:</span>
                    <?php if ($_imageSwatch): ?>
                        <img class="swatch-shopby-selected" src="<?php echo $_imageSwatch ?>" title="<?php echo $label ?>" alt="<?php echo $label ?>">
                    <?php elseif ($_bgSwatch): ?>
                        <span class="swatch-shopby-selected swatches-has-bg" style="background-color:<?php echo $_bgSwatch ?>" title="<?php echo $label ?>"></span>
                        <?php else: ?>
                            <span class="filter-selected"><?php echo $label ?></span>
                        <?php endif; ?>
                </li>

            <?php else : ?>
                <li>
                    <a href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo $this->__('Remove This Item') ?>" class="btn-remove"><?php echo $this->__('Remove This Item') ?></a>
                    <span class="label"><?php echo $this->__($_filter->getName()) ?>:</span> <?php echo $this->stripTags($_filter->getLabel()) ?>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ol>
    <?php /* div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div */ ?>
</div>
