<?php
$_collection = $this->getCollection();
$_catalogHelper = $this->helper('catalog/image');
$_size = 100;
?>
<?php echo $this->getPagerHtml(); ?>
<table class="data-table products-selection-bundle">
    <thead>
    <tr>
        <th class="mp-check"><?php echo $this->__('Check') ?></th>
        <th class="mp-id"><?php echo $this->__('Id') ?></th>
        <th class="mp-image"><?php echo $this->__('Image') ?></th>
        <th class="mp-name"><?php echo $this->__('Name') ?></th>
        <th class="mp-sku"><?php echo $this->__('Sku') ?></th>
        <th class="mp-price"><?php echo $this->__('Price') ?></th>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($_collection as $_product): ?>
            <?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
            <tr>
                <td class="mp-check" for="product-<?php echo $_product->getId(); ?>">
                    <input type="checkbox" name="bundle_options[0][product][]" value="<?php echo $_product->getId(); ?>" id="product-<?php echo $_product->getId(); ?>"<?php if(in_array($_product->getId(),$_associatedProduct)) {echo ' checked';} ?>>
                </td>
                <td class="mp-id"><?php echo $_product->getId() ?></td>
                <td class="mp-image"><a href="<?php echo $_product->getProductUrl(); ?>"><img src="<?php echo $_catalogHelper->init($_product, 'small_image')->resize($_size, $_size); ?>" /></a></td>
                <td class="mp-name"><span class="nobr"><?php echo $_product->getName() ?></span></td>
                <td class="mp-sku"><span class="nobr"><?php echo $_product->getSku() ?></span></td>
                <td class="mp-price"><?php echo $this->helper('core')->currency($_product->getPrice(),true,false); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
</table>