{{block type="catalogg/product_new" name="home_product_new" limit="20" column="4"}}
{{block type="catalogg/product_sale" name="home_product_sale" limit="20" column="4"}}
{{block type="catalogg/product_bestseller" name="home_product_bestseller" limit="20" column="4"}}
{{block type="catalogg/product_recently" name="home_product_recently" limit="20" column="4"}}
{{block type="catalogg/product_categories" name="home_product_category" limit="20" column="4" categories="4"}}