<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<div class="post-list-wrapper">
    <?php if (count($posts)): ?>
        <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
        <div class="post-list">
            <?php foreach ($posts as $post): ?>
                <div class="post-item">
                    <div class="post-title">
                        <h2><a href="<?php echo $post->getAddress(); ?>"><?php echo $post->getTitle(); ?></a></h2>

                        <h3><?php echo $post->getCreatedTime(); ?></h3>
                    </div>
                    <div class="post-content std"><?php echo $post->getPostContent(); ?></div>

                    <?php echo $this->getBookmarkHtml($post) ?>
                    <div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
                    <div class="post-details">
                        <?php if ($this->getCommentsEnabled()): ?>
                            <?php echo $post->getCommentCount(); ?> <a
                                href="<?php echo $post->getAddress(); ?>#commentBox"> <?php echo Mage::helper('blog')->__('Comments'); ?></a> |
                        <?php endif; ?>
                        <?php $postCats = $post->getCats(); ?>
                        <?php if (!empty($postCats)): ?>
                            <?php echo Mage::helper('blog')->__('Posted in'); ?>
                            <?php foreach ($postCats as $data): ?>
                                <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <?php echo Mage::helper('blog')->__('Posted'); ?>
                        <?php endif; ?><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?></div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>

    <?php else: ?>
        <p class="post-empty"><?php echo $this->__('Not found post!'); ?></p>
    <?php endif; ?>
</div>