<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<div class="post-list-wrapper">
    <div class="block-search-post">
        <form action="<?php echo $this->getUrl('blog/index/search'); ?>" method="get">
            <ul class="form-list">
                <li class="" fields>
                    <div class="field">
                        <?php $years = $this->getYears(); ?>
                        <?php $paramYear = $this->getRequest()->getParam('year'); ?>
                        <label><?php echo $this->__('Year'); ?></label>
                        <div class="input-box">
                            <select name="year" class="input-select">
                                <option value=""></option>
                                <?php if (count($years)): ?>
                                    <?php foreach($years as $yearKey => $yearValue): ?>
                                        <option value="<?php echo $yearKey; ?>"<?php if($paramYear==$yearKey) echo ' selected'; ?>><?php echo $yearValue; ?></option>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </select>
                        </div>
                    </div>
                    <div class="field">
                        <?php $months = $this->getMonth(); ?>
                        <?php $paramMonth = $this->getRequest()->getParam('month'); ?>
                        <label><?php echo $this->__('Month'); ?></label>
                        <div class="input-box">
                            <select name="month" class="input-select">
                                <option value=""></option>
                                <?php if (count($months)): ?>
                                    <?php foreach($months as $monthKey => $monthValue): ?>
                                        <option value="<?php echo $monthKey; ?>"<?php if($paramMonth==$monthKey) echo ' selected'; ?>><?php echo $monthValue; ?></option>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </select>
                        </div>
                    </div>
                    <div class="field">
                        <label><?php echo $this->__('Text'); ?></label>
                        <div class="input-box">
                            <input class="input-text" type="text" name="q" />
                        </div>
                    </div>
                    <div class="field">
                        <button type="submit" class="button btn-summit">
                            <span><?php echo $this->__('Search'); ?></span>
                        </button>
                    </div>
                </li>
            </ul>
        </form>
    </div>

    <?php if (count($posts)): ?>
        <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
        <div class="post-list">
            <?php foreach ($posts as $post): ?>
                <div class="post-item">
                    <div class="post-title">
                        <h2><a href="<?php echo $post->getAddress(); ?>"><?php echo $post->getTitle(); ?></a></h2>

                        <h3><?php echo $post->getCreatedTime(); ?></h3>
                    </div>
                    <div class="post-content std"><?php echo $post->getPostContent(); ?></div>

                    <?php echo $this->getBookmarkHtml($post) ?>
                    <div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
                    <div class="post-details">
                        <?php if ($this->getCommentsEnabled()): ?>
                            <?php echo $post->getCommentCount(); ?> <a
                                href="<?php echo $post->getAddress(); ?>#commentBox"> <?php echo Mage::helper('blog')->__('Comments'); ?></a> |
                        <?php endif; ?>
                        <?php $postCats = $post->getCats(); ?>
                        <?php if (!empty($postCats)): ?>
                            <?php echo Mage::helper('blog')->__('Posted in'); ?>
                            <?php foreach ($postCats as $data): ?>
                                <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <?php echo Mage::helper('blog')->__('Posted'); ?>
                        <?php endif; ?><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?></div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>

    <?php else: ?>
        <p class="post-empty"><?php echo $this->__('Not found post!'); ?></p>
    <?php endif; ?>
</div>