<?php
$collection = $this->getCollection();
if ($collection->count() > 0) {
    $_helper = $this->helper('sliderg');
    $prefixId = '-' . md5(mt_rand());
    $config = $this->getConfig();
    $width = $config->getData('width');
    $height = $config->getData('height');
?>
    <div class="sb-box">
        <ul id="sb-slider<?php echo $prefixId; ?>" class="sb-slider sb-slider<?php echo $prefixId; ?>">
            <?php
            foreach ($collection as $image) {
                if($width && $height) {
                    $size = $_helper->getImageSize($image, $width, $height);
                }
                elseif ($width) {
                    $size = $_helper->getImageSize($image, $width);
                }
                else {
                    $size = $_helper->getImageSize($image);
                }
                ?>
                <li>
                    <a href="<?php echo $this->helper('baseg')->translateCode($image->getUrlBanner()); ?>">
                        <img
                            src="<?php echo $this->helper('sliderg/image')->init($image->getPathMedia())->resize($size->getWidth(), $size->getHeight()); ?>"/>
                    </a>

                    <div class="sb-description">
                        <p><?php echo $image->getDescription(); ?></p>
                    </div>
                </li>
            <?php }//end foreach collection image ?>
        </ul>

        <div id="shadow<?php echo $prefixId; ?>" class="shadow"></div>

        <div id="nav-arrows<?php echo $prefixId; ?>" class="nav-arrows">
            <a href="#" class="next">Next</a>
            <a href="#" class="prev">Previous</a>
        </div>

        <div id="nav-dots<?php echo $prefixId; ?>" class="nav-dots">
            <?php for ($i = 0; $i < $collection->count(); $i++) {
                echo '<span></span>';
            }
            ?>
        </div>
    </div>
    <script>
        jQuery(document).ready(function ($) {
            var Page = (function () {
                var $navArrows = $('#nav-arrows<?php echo $prefixId;?>').hide(),
                    $navDots = $('#nav-dots<?php echo $prefixId;?>').hide(),
                    $nav = $navDots.children('span'),
                    $shadow = $('#shadow<?php echo $prefixId;?>').hide(),
                    slicebox = $('#sb-slider<?php echo $prefixId;?>').slicebox({
                        onReady: function () {
                            $navArrows.show();
                            $navDots.show();
                            $shadow.show();

                        },
                        onBeforeChange: function (pos) {
                            $nav.removeClass('nav-dot-current');
                            $nav.eq(pos).addClass('nav-dot-current');
                        },
                        <?php if($config->getData('setting_more')) {echo $config->getData('setting_more').',';} ?>

                        // callbacks
                        //onBeforeChange : function( position ) { return false; },
                        onAfterChange: function (position) {
                            return false;
                        }
                    }),
                    init = function () {
                        initEvents();
                    },
                    initEvents = function () {
                        // add navigation events
                        $navArrows.children('.next').on('click', function () {
                            slicebox.next();
                            return false;
                        });
                        $navArrows.children('.prev').on('click', function () {
                            slicebox.previous();
                            return false;
                        });
                        $nav.each(function (i) {
                            $(this).on('click', function (event) {
                                var $dot = $(this);
                                if (!slicebox.isActive()) {
                                    $nav.removeClass('nav-dot-current');
                                    $dot.addClass('nav-dot-current');
                                }
                                slicebox.jump(i + 1);
                                return false;
                            });
                        });
                    };
                return {init: init};
            })();
            Page.init();
        });
    </script>
<?php }//endif count images ?>