<?php
$collection = $this->getCollection();
$_helper = $this->helper('sliderg');
echo "<br/>";
if($collection->count() > 0) {
    foreach($collection as $image) {
        $size = $_helper->getImageSize($image,300,300);
        if($size) {
            echo "Link: ".$_helper->getImageUrl($image->getPathMedia());
            echo "<br/>";
            echo "path: ".$this->helper('sliderg/image')->init($image->getPathMedia())->resize($size->getWidth(), $size->getHeight());
            echo "<br/>";
            echo "url link to: ". $this->helper('baseg')->translateCode($image->getUrlBanner());
            echo "<br/><br/><br/>";
        }
    }//end foreach collection image
}//endif count collection image
