<?php
	$_product = $this->getProduct();
	if(!$_product) {
		return;
	}
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="seller-page seller-product-configuration">
	<h1 class="page-title"><?php 
		echo $this->__('Edit configuration product: %s',$_product->getName()); 
	?></h1>
	<div class="form-seller-add-product">
		<form method="post" action="<?php echo $this->getUrl('seller/product/associalPost'); ?>" id="form-seller-product-configuration" enctype="multipart/form-data">
			<?php echo $this->getBlockHtml('formkey'); ?>
			<input type="hidden" name="entity_id" value="<?php echo $_product->getId(); ?>" />
			<?php echo $this->getChildHtml('seller_product_list_associated'); ?>
			<div class="button-sets">
				<button type="submit" class="btn btn-add-product">
					<span><?php echo $this->__('Save Product'); ?></span>
				</button>
			</div>
		</form>
	</div>
</div>
<script type="text/javascript">
	
</script>