<?php
	$_product = $this->getProduct();
	$_formData = $this->getFormData();
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="seller-page seller-product-add">
	<h1 class="page-title"><?php 
		if($_product) {
			echo $this->__('Edit product: %s',$_product->getName());
		}
		else {
			echo $this->__('Add product');
		}
	?></h1>
	<div class="form-seller-product">
		<form method="post" action="<?php echo $this->getUrl('sellerg/product/save'); ?>" id="form-seller-product" enctype="multipart/form-data">
			<?php echo $this->getBlockHtml('formkey'); ?>
			<input type="hidden" name="entity_id" value="<?php echo $_formData->getId(); ?>" />
			<div class="button-sets">
				<button type="submit" class="btn btn-add-product">
					<span><?php echo $this->__('Save Product'); ?></span>
				</button>
			</div>
	        <ul class="tabs">
	            <li id="product_tabs_1" class="active first"><a href="#"><?php echo $this->__('General') ?></a></li>
	            <li id="product_tabs_2" ><a href="#"><?php echo $this->__('Images') ?></a></li>
	            <li id="product_tabs_3" ><a href="#"><?php echo $this->__('Categories') ?></a></li>
				<?php if($this->isConfigurableProduct()): ?>
	            	<li id="product_tabs_4" ><a href="#"><?php echo $this->__('Associated Products') ?></a></li>
	            <?php endif; ?>
	        </ul>
	        <div class="padder">
	            <div id="product_tabs_1_contents">
	            	<?php echo $this->getChildHtml('seller_product_general'); ?>
	            </div>
	            <div id="product_tabs_2_contents">
	            	<?php echo $this->getChildHtml('seller_product_images'); ?>
	            </div>
	            <div id="product_tabs_3_contents">
	            	<?php echo $this->getChildHtml('seller_product_categories'); ?>
	            </div>
	            <?php if($this->isConfigurableProduct()): ?>
	            	<div id="product_tabs_4_contents">
	            		<?php echo $this->getChildHtml('seller_product_configurable'); ?>
	            	</div>
	            <?php endif; ?>
	        </div>
		</form>
		<script type="text/javascript">
		//<![CDATA[
		    new Varien.Tabs('.tabs');
		    new VarienForm('form-seller-product');
		//]]>
		</script>
		<?php /*form method="post" action="<?php echo $this->getUrl('seller/product/save'); ?>" id="form-seller-add-product" enctype="multipart/form-data">
			<?php echo $this->getBlockHtml('formkey'); ?>
			<?php if(!$_product) : ?>
				<input type="hidden" name="attribute_set_id" value="<?php echo $this->getAttributeSetId(); ?>" />
			<?php else : ?>
				<input type="hidden" name="entity_id" value="<?php echo $_product->getId(); ?>" />
			<?php endif; ?>
			<div class="form-category-list">
				<h3 class="category-list-title click-category show-hide"><?php echo $this->__('Choose category +'); ?></h3>
				<?php echo $this->getCategoryTree(); ?>
				<div class="click-category hide"><?php echo $this->__('Hide category'); ?></div>
			</div>
			<?php if($_formData->getTypeId() == 'configurable'): ?>
				<div class="associated-configuration">
					<h4><a href="<?php echo $this->getUrl('seller/product/configurable',array('id'=>$_product->getId())); ?>"><?php echo $this->__('Add Associated Product'); ?></a></h4>
				</div>
			<?php endif; ?>
			<ul class="form-list">
				<li class="fields">
					<div class="field">
						<?php 
							$_productImage = $_formData->getData('image');
							if($_productImage) {
								if($_productImage) { ?>
									<span class="product-image">
										<img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(100,100) ?>" title="" alt="" class="small-image-preview v-middle" height="100" width="100">
									</span>
								<?php }
							} ?>
	                	<input id="product_image" name="product_image" value="<?php echo $_productImage; ?>" class="input-file" type="file">
		                <?php if ( $_productImage ) : ?>
		                    <div class="delete-image">
		                        <input name="product_image_delete" value="1" class="checkbox" id="product_image_delete" type="checkbox" />
		                        <label for="product_image_delete"> Delete Image</label>
		                    </div>
		                <?php endif; ?>
	                </div>
	            </li>
				<li class="fields">
					<div class="field">
						<label class="required" for="name"><?php echo $this->__('Name'); ?><em>*</em></label>
						<div class="input-box">
							<input type="text" name="name" value="<?php echo $_formData->getName(); ?>" class="input-text required-entry" id="name"/>
						</div>
					</div>
					<div class="field">
						<label class="required" for="sku"><?php echo $this->__('Sku'); ?><em>*</em></label>
						<div class="input-box">
							<input type="text" name="sku" value="<?php echo $_formData->getSku(); ?>" class="input-text required-entry" id="sku" />
						</div>
					</div>
				</li>
				<?php if(!$_product): ?>
					<?php if($this->isRentProduct()): ?>
						<input type="hidden" name="type_id" value="simple" />
					<?php else: ?>
						<li class="fields">
							<div class="field">
								<label for="type_id"><?php echo $this->__('Type'); ?></label>
								<div class="input-box">
									<select name="type_id" id="type_id" class="input-select">
										<option value="simple"><?php echo $this->__('Simple'); ?></option>
										<option value="configurable"><?php echo $this->__('Configurable'); ?></option>
									</select>
								</div>
							</div>
						</li>
					<?php endif; ?>
				<?php endif; ?>
				<li class="filds">
					<div class="field">
						<label class="required" for="weight"><?php echo $this->__('Weight'); ?><em>*</em></label>
						<div class="input-box">
							<input type="text" name="weight" value="<?php echo $_formData->getData('weight'); ?>" class="input-text required-entry validate-number" id="weight" />
						</div>
					</div>
					<?php $_countries = $this->getCountryOptions(); ?>
					<?php if(count($_countries) > 0) { ?>
						<div class="field">
							<label for="country_of_manufacture"><?php echo $this->__('Country'); ?></label>
							<div class="input-box">
								<select name="country_of_manufacture" id="country_of_manufacture">
									<option value=""></option>
									<?php foreach($_countries as $_country) { ?>
										<option value="<?php echo $_country['value']; ?>"<?php if($_formData->getData('country_of_manufacture') == $_country['value']) {echo ' selected';} ?>><?php echo $_country['label']; ?></option>
									<?php } //end foreach country ?>
								</select>
							</div>
						</div>
					<?php } //endif check count country ?>
				</li>
				<li class="fields">
					<div class="field">
						<label for="status"><?php echo $this->__('Status'); ?></label>
						<div class="input-box">
							<select name="status" id="status">
								<option value="1"<?php if($_product && $_product->getData('status') ==1 ){ echo 'selected';}?>><?php echo $this->__('Enable'); ?></option>
								<option value="2"<?php if($_product && $_product->getData('status') != 1){ echo 'selected';}?>><?php echo $this->__('Disable'); ?></option>
							</select>
						</div>
					</div>
					<div class="field">
						<label for="warranty"><?php echo $this->__('Warranty'); ?></label>
						<div class="input-box">
							<input type="text" name="warranty" value="<?php echo $_formData->getData('warranty'); ?>" class="input-text" id="warranty" />
						</div>
					</div>
				</li>
				<li class="fields">
					<div class="field">
						<label class="required" for="price"><?php echo $this->__('Price'); ?><em>*</em></label>
						<div class="input-box">
							<input type="text" name="price" value="<?php echo $_formData->getData('price'); ?>" class="input-text required-entry validate-number" id="price" />
						</div>
					</div>
					<div class="field">
						<label for="special_price"><?php echo $this->__('Special Price'); ?></label>
						<div class="input-box">
							<input type="text" name="special_price" value="<?php echo $_formData->getData('special_price'); ?>" class="input-text validate-number" id="special_price" />
						</div>
					</div>
				</li>
				<?php $_options = $this->getClassTax(); ?>
				<?php if(count($_options) > 0) { ?>
					<li class="fields">
						<div class="field">
							<label class="required" for="tax_class_id"><?php echo $this->__('Tax Class'); ?><em>*</em></label>
							<div class="input-box">
								<select name="tax_class_id" value="" class="input-select validate-select" id="tax_class_id">
									<option value=""></option>
									<?php foreach($_options as $_option) { ?>
										<option value="<?php echo $_option['value']; ?>"<?php if($_formData->getData('tax_class_id') == $_option['value']) {echo ' selected';} ?>><?php echo $_option['label']; ?></option>
									<?php } // end for options ?>
								</select>
							</div>
						</div>
					</li>
				<?php } //endif check count options ?>
				<li class="fields">
					<div class="field">
						<label for="special_from_date"><?php echo $this->__('Special From Date'); ?></label>
						<div class="input-box">
							<input name="special_from_date" id="special_from_date" class="input-text" readonly="readonly" value="<?php 
								if($_formData->getData('special_from_date')) {
									$date = date_create($_formData->getData('special_from_date')); 
									echo date_format($date, 'Y-m-d');
								}
								?>" id="special_from_date" />
						</div>
					</div>
					<div class="field">
						<label for="special_to_date"><?php echo $this->__('Special To Date'); ?></label>
						<div class="input-box">
							<input name="special_to_date" id="special_to_date" class="input-text" readonly="readonly" value="<?php 
								if($_formData->getData('special_to_date')) {
									$date = date_create($_formData->getData('special_to_date')); 
									echo date_format($date, 'Y-m-d');
								}
								?>" id="special_to_date" />
						</div>
					</div>
				</li>
				<?php if($this->isRentProduct()) { ?>
					<li class="fields">
						<div class="field">
							<label for="price_daily"><?php echo $this->__('Price Daily'); ?></label>
							<div class="input-box">
								<input type="text" name="price_daily" class="input-text" value="<?php echo $_formData->getData('price_daily'); ?>" id="price_daily" />
							</div>
						</div>
						<div class="field">
							<label for="price_weekly"><?php echo $this->__('Price Weekly'); ?></label>
							<div class="input-box">
								<input type="text" name="price_weekly" class="input-text" value="<?php echo $_formData->getData('price_weekly'); ?>" id="price_weekly" />
							</div>
						</div>
					</li>
					<li class="fields">
						<div class="field">
							<label for="price_monthly"><?php echo $this->__('Price Monthly'); ?></label>
							<div class="input-box">
								<input type="text" name="price_monthly" class="input-text" value="<?php echo $_formData->getData('price_monthly'); ?>" id="price_monthly" />
							</div>
						</div>
					</li>
				<?php } //end check rent product ?>
				<li class="fields">
					<div class="field">
						<label for="inventory_stock_availability"><?php echo $this->__('Stock Availability'); ?></label>
						<div class="input-box">
							<select name="inventory_stock_availability" id="inventory_stock_availability">
								<option value="1"<?php if($_product && $_product->getData('is_in_stock')){ echo 'selected';}?>><?php echo $this->__('In Stock'); ?></option>
								<option value="0"<?php if($_product && !$_product->getData('is_in_stock')){ echo 'selected';}?>><?php echo $this->__('Out Stock'); ?></option>
							</select>
						</div>
					</div>
					<div class="field">
						<label class="required" for="qty"><?php echo $this->__('Qty'); ?><em>*</em></label>
						<div class="input-box">
							<input type="text" name="qty" class="input-text required-entry validate-number" value="<?php if($_product) echo $_product->getStockItem()->getQty(); ?>" id="qty" />
						</div>
					</div>
				</li>
				<li class="fields">
					<div class="field">
						<label class="required" for="short_description"><?php echo $this->__('Short Description'); ?><em>*</em></label>
						<div class="input-box">
							<input type="text" id="short_description" name="short_description" class="input-text required-entry" value="<?php echo $_formData->getData('short_description'); ?>" />
						</div>
					</div>
				</li>
				<li class="fields">
					<div class="field">
						<label class="required" for="description"><?php echo $this->__('Description'); ?><em>*</em></label>
						<div class="input-box">
							<input type="text" id="description" name="description" class="input-text required-entry" value="<?php echo $_formData->getData('description'); ?>"/>
						</div>
					</div>
				</li>
				<?php if(!$this->isRentProduct()) { ?>
					<li class="fields">
						<?php $_options = $this->getAttributeOptions('color'); ?>
						<?php if(count($_options) > 0) { ?>
							<div class="field">
								<label for="color"><?php echo $this->__('Color'); ?></label>
								<div class="input-box">
									<select type="text" name="color" class="" id="color">
										<option value=""></option>
										<?php foreach($_options as $_option) { ?>
											<option value="<?php echo $_option['value']; ?>"<?php if($_formData->getData('color') == $_option['value']) {echo ' selected';} ?>><?php echo $_option['label']; ?></option>
										<?php }; //end foreach options ?>
									</select>
								</div>
							</div>
						<?php } //endif check count options ?>
						<?php $_options = $this->getAttributeOptions('size'); ?>
						<?php if(count($_options) > 0) { ?>
							<div class="field">
								<label for="size"><?php echo $this->__('Size'); ?></label>
								<div class="input-box">
									<select type="text" name="size" class="" id="size">
										<option value=""></option>
										<?php foreach($_options as $_option) { ?>
											<option value="<?php echo $_option['value']; ?>"<?php if($_formData->getData('size') == $_option['value']) {echo ' selected';} ?>><?php echo $_option['label']; ?></option>
										<?php }; //end foreach options ?>
									</select>
								</div>
							</div>
						<?php } //endif check count options ?>
					</li>
				<?php }//endif check not rent ?>
				<li class="fields">
					<div class="field">
						<label for="width"><?php echo $this->__('Width'); ?></label>
						<div class="input-box">
							<input type="text" name="width" class="input-text" value="<?php echo $_formData->getData('width'); ?>" id="width" />
						</div>
					</div>
					<div class="field">
						<label for="depth"><?php echo $this->__('Depth'); ?></label>
						<div class="input-box">
							<input type="text" name="depth" class="input-text" value="<?php echo $_formData->getData('depth'); ?>" id="depth" />
						</div>
					</div>
				</li>
				<li class="fields">
					<div class="field">
						<label for="height"><?php echo $this->__('Height'); ?></label>
						<div class="input-box">
							<input type="text" name="height" class="input-text" value="<?php echo $_formData->getData('height'); ?>" id="height" />
						</div>
					</div>
					<div class="field">
						<label for="style"><?php echo $this->__('Style'); ?></label>
						<div class="input-box">
							<input type="text" name="style" class="input-text" value="<?php echo $_formData->getData('style'); ?>" id="style" />
						</div>
					</div>
				</li>
			</ul>
			<div class="button-sets">
				<button type="submit" class="btn btn-add-product">
					<span><?php echo $this->__('Save Product'); ?></span>
				</button>
			</div>
		</form*/ ?>
	</div>
</div>
