<?php
$_product = $this->getProduct();
if(!$_product) {
	return;
}
?>
<?php $_collection = $this->getCollection(); ?>
<?php $_catalogHelper = $this->helper('catalog/image'); ?>
<?php $_size = 100; ?>
<?php echo $this->getPagerHtml(); ?>
<?php if($_collection->getSize()): ?>
	<?php $_associatedProduct = $this->getAssociatedProducts(); ?>
	<table class="data-table" id="my-products-associated">
		<col width="1" />
		<col width="1" />
		<col />
		<col width="1" />
		<col width="1" />
		<col width="1" />
		<col width="1" />
		<thead>
		<tr>
			<th class="mp-check"><?php echo $this->__('Check') ?></th>
			<th class="mp-id"><?php echo $this->__('#') ?></th>
			<th class="mp-image"><?php echo $this->__('Image') ?></th>
			<th class="mp-name"><?php echo $this->__('Name') ?></th>
			<th class="mp-color"><?php echo $this->__('Color') ?></th>
			<th class="mp-size"><?php echo $this->__('Size') ?></th>
			<th class="mp-price"><span class="nobr"><?php echo $this->__('Price') ?></span></th>
		</tr>
		</thead>
		<tbody>
		<?php foreach ($_collection as $_product): ?>
			<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
			<tr>
				<td class="mp-check" for="product-<?php echo $_product->getId(); ?>">
					<input type="checkbox" name="associated[]" value="<?php echo $_product->getId(); ?>" id="product-<?php echo $_product->getId(); ?>"<?php if(in_array($_product->getId(),$_associatedProduct)) {echo ' checked';} ?>>
				</td>
				<td class="mp-id"><?php echo $_product->getId() ?></td>
				<td class="mp-image"><a href="<?php echo $_product->getProductUrl(); ?>"><img src="<?php echo $_catalogHelper->init($_product, 'small_image')->resize($_size, $_size); ?>" /></a></td>
				<td class="mp-name"><span class="nobr"><?php echo $_product->getName() ?></span></td>
				<td class="mp-color"><span class="nobr"><?php
						if($_product->getData('color')) {
							$_attributeValue = $_product->getResource()->getAttribute('color');
							echo $_attributeValue->getFrontend()->getValue($_product);
						}
						?></span></td>
				<td class="mp-size"><span class="nobr"><?php
						if($_product->getData('size')) {
							$_attributeValue = $_product->getResource()->getAttribute('size');
							echo $_attributeValue->getFrontend()->getValue($_product);
						}
						?></span></td>
				<td class="mp-price"><?php echo $_product->getPrice() ?></td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
	<script type="text/javascript">decorateTable('my-products-associated');</script>
	<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
	<p><?php echo $this->__('You have no product to display.'); ?></p>
<?php endif ?>
