<?php
$_product = $this->getProduct();
$_formData = $this->getFormData();
$_sHelper = $this->helper('sellerg');
$_attributes = $this->attributes();
$_fieldsShow = $this->fieldsShow();
$_arrayFieldWysiwyg = array();
?>

<script type="text/javascript">
    function calendarSetup(id) {
        Calendar.setup({
            inputField: id,
            ifFormat: '%Y-%m-%d',
            showsTime: false,
            button: id,
            align: 'Bl',
            singleClick: true
        });
    }
    enUS = {
        "m": {
            "wide": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
            "abbr": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        }
    }; // en_US locale reference
    Calendar._DN = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]; // full day names
    Calendar._SDN = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]; // short day names
    Calendar._FD = 0; // First day of the week. "0" means display Sunday first, "1" means display Monday first, etc.
    Calendar._MN = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]; // full month names
    Calendar._SMN = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]; // short month names
    Calendar._am = "AM"; // am/pm
    Calendar._pm = "PM";

    // tooltips
    Calendar._TT = {};
    Calendar._TT["INFO"] = 'About the calendar';

    Calendar._TT["ABOUT"] =
        'DHTML Date/Time Selector\n' +
        "(c) dynarch.com 2002-2005 / Author: Mihai Bazon\n" +
        'For latest version visit: http://www.dynarch.com/projects/calendar/\n' +
        'Distributed under GNU LGPL. See http://gnu.org/licenses/lgpl.html for details.' +
        '\n\n' +
        'Date selection:\n' +
        '- Use the \xab, \xbb buttons to select year\n' +
        '- Use the \u2039 buttons to select month\n' +
        '- Hold mouse button on any of the above buttons for faster selection.';
    Calendar._TT["ABOUT_TIME"] = '\n\n' +
    'Time selection:\n' +
    '- Click on any of the time parts to increase it\n' +
    '- or Shift-click to decrease it\n' +
    '- or click and drag for faster selection.';

    Calendar._TT["PREV_YEAR"] = 'Prev. year (hold for menu)';
    Calendar._TT["PREV_MONTH"] = 'Prev. month (hold for menu)';
    Calendar._TT["GO_TODAY"] = 'Go Today';
    Calendar._TT["NEXT_MONTH"] = 'Next month (hold for menu)';
    Calendar._TT["NEXT_YEAR"] = 'Next year (hold for menu)';
    Calendar._TT["SEL_DATE"] = 'Select date';
    Calendar._TT["DRAG_TO_MOVE"] = 'Drag to move';
    Calendar._TT["PART_TODAY"] = ' (' + "today" + ')';

    // the following is to inform that "%s" is to be the first day of week
    Calendar._TT["DAY_FIRST"] = 'Display %s first';

    // This may be locale-dependent. It specifies the week-end days, as an array
    // of comma-separated numbers. The numbers are from 0 to 6: 0 means Sunday, 1
    // means Monday, etc.
    Calendar._TT["WEEKEND"] = "0,6";

    Calendar._TT["CLOSE"] = 'Close';
    Calendar._TT["TODAY"] = "today";
    Calendar._TT["TIME_PART"] = '(Shift-)Click or drag to change value';

    // date formats
    Calendar._TT["DEF_DATE_FORMAT"] = "%Y-%m-%d";
    Calendar._TT["TT_DATE_FORMAT"] = "%Y-%m-%d";

    Calendar._TT["WK"] = "Week";
    Calendar._TT["TIME"] = 'Time:';
    function loadWysiwyg(id) {
        tinyMCE.init({
            mode: "exact",
            elements: id,
            theme: "advanced",
            plugins: "inlinepopups,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
            theme_advanced_buttons1: "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,|,visualchars,nonbreaking",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left",
            theme_advanced_path_location: "bottom",
            extended_valid_elements: "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
            theme_advanced_resize_horizontal: 'true',
            theme_advanced_resizing: 'true',
            apply_source_formatting: 'true',
            convert_urls: 'false',
            force_br_newlines: 'true',
            doctype: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'

        });
    }
</script>

<div class="form-general">
    <ul class="form-list">
        <?php foreach ($_fieldsShow as $_fieldShowRow) { ?>
            <li class="fields">
                <?php foreach ($_fieldShowRow as $_code => $_field) { ?>
                    <?php
                    $_optionField = array();
                    if(is_array($_field)) {
                        $_fieldData = $_attributes[$_code];
                        $_optionField = $_field;
                    }
                    else {
                        $_fieldData = $_attributes[$_field];
                    }
                    if(!$_fieldData) {
                        $_fieldData = $_field;
                    }
                    if(!is_array($_fieldData)) {
                        continue;
                    }
                    if($_formData->getId()) {
                        $_applyToTypes = $_fieldData['apply_to'];
                        if($_applyToTypes) {
                            $_applyToTypes = explode(',', $_applyToTypes);
                            if (!in_array($_formData->getData('type_id'), $_applyToTypes)) {
                                continue;
                            }
                        }
                    }
                    $_classField = '';
                    $_classFor = '';
                    $_symbolFor = '';
                    if ($_fieldData['is_required']) {
                        $_classFor .= ' required';
                        $_symbolFor .= ' <em>*</em>';
                        if ($_fieldData['frontend_input'] == 'text') {
                            $_classField .= ' required-entry';
                        } elseif ($_fieldData['frontend_input'] == 'select') {
                            $_classField .= ' validate-select';
                        } else {
                            $_classField .= ' required-entry';
                        }
                    }
                    $_classField .= ' input-' . $_fieldData['frontend_input'];
                    ?>
                    <div class="field">
                        <label class="<?php echo $_classFor; ?>"
                               for="<?php echo $_fieldData['attribute_code']; ?>"><?php echo $_fieldData['frontend_label']; ?>
                            <?php echo $_symbolFor; ?></label>

                        <div class="input-box">
                            <?php if ($_fieldData['is_wysiwyg_enabled']) { ?>
                                <input type="<?php echo $_fieldData['frontend_input']; ?>"
                                       name="<?php echo $_fieldData['attribute_code']; ?>"
                                       value="<?php echo $_formData->getData($_fieldData['attribute_code']); ?>"
                                       class="<?php echo $_classField; ?>"
                                       id="<?php echo $_fieldData['attribute_code']; ?>"/>
                                <?php $_arrayFieldWysiwyg[] = $_fieldData['attribute_code']; ?>
                            <?php
                            } else {
                                switch ($_fieldData['frontend_input']) {
                                    case 'textarea':
                                        echo "<textarea
                                       name=\"{$_fieldData['attribute_code']}\"
                                       class=\"{$_classField}\"
                                       id=\"{$_fieldData['attribute_code']}\">{$_formData->getData($_fieldData['attribute_code'])}</textarea>";
                                        break;
                                    case 'select':
                                        echo "<select name=\"{$_fieldData['attribute_code']}\"
                                         id=\"{$_fieldData['attribute_code']}\"
                                         class=\"{$_classField}\">";
                                        if($_fieldData['source_model']) {
                                            $_options = Mage::getModel($_fieldData['source_model'])->getAllOptions();
                                        }
						                else {
                                            $_options = $this->getAttributeOptions($_fieldData['attribute_code']);
                                        }
						                if(count($_options)) {
							                foreach ($_options as $option) {
								                echo "<option value=\"{$option['value']}\"";
                                                if($_formData->getData($_fieldData['attribute_code']) == $option['value']) {
                                                    echo ' selected';
                                                }
                                                echo ">{$option['label']}</option>";
							                }
                                        }
                                        echo '</select>';
                                        break;
                                    default:
                                        echo "<input type=\"text\"
                                       name=\"{$_fieldData['attribute_code']}\"
                                       value=\"{$_formData->getData($_fieldData['attribute_code'])}\"
                                       class=\"{$_classField}\"
                                       id=\"{$_fieldData['attribute_code']}\"/>";
                                        if($_fieldData['frontend_input'] == 'date') {
                                            echo "<script>calendarSetup('{$_fieldData['attribute_code']}');</script>";
                                        }
                                        break;
                                } ?>
                            <?php } ?>
                        </div>
                    </div>
                <?php }//end foreach field ?>
            </li>
        <?php }//endforeach field array row ?>
    </ul>
</div>

<script>
    window.onload = function () {
        <?php foreach($_arrayFieldWysiwyg as $_fieldWysiwyg): ?>
        loadWysiwyg('<?php echo $_fieldWysiwyg; ?>');
        <?php endforeach; ?>
    };
</script>