<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
$prefixId = '-' . md5(mt_rand());
$_helperZoom = $this->helper('zoomg');
$_width = $_helperZoom->getGeneralConfig('width');
if(!$_width) {
    $_width = 265;
}
?>
<?php /*
    <div class="swiper-container gallery-top swiper-gallery-top<?php echo $prefixId; ?>">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <?php
                    $_img = '<img'.
                        ' src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" '.
                        ' data-zoom-image="'.$this->helper('catalog/image')->init($_product, 'image').'"'.
                        ' alt="'.$this->escapeHtml($this->getImageLabel()).'" title="'.$this->escapeHtml($this->getImageLabel()).'" />';
                    echo $_helper->productAttribute($_product, $_img, 'image');
                ?>
            </div>
            <?php if (count($this->getGalleryImages()) > 0): ?>
                <?php foreach ($this->getGalleryImages() as $_image): ?>
                    <div class="swiper-slide">
                        <img
                             src="<?php echo $this->helper('catalog/image')->init($_product, 'image', $_image->getFile())->resize(265); ?>"
                             width="265" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>"
                             data-zoom-image="<?php echo $this->helper('catalog/image')->init($_product, 'image', $_image->getFile()); ?>"'  />
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
        <!-- Add Arrows -->
        <div class="swiper-button-next-top<?php echo $prefixId; ?> swiper-button-next swiper-button-next-top"></div>
        <div class="swiper-button-prev-top<?php echo $prefixId; ?> swiper-button-prev swiper-button-prev-top"></div>
    </div>

<?php if (count($this->getGalleryImages()) > 0): ?>
    <div class="swiper-container gallery-thumbs swiper-gallery-thumbs<?php echo $prefixId; ?>">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <?php
                $_img = '<img'.
                    ' src="'.$this->helper('catalog/image')->init($_product, 'thumbnail')->resize(56).'" '.
                    ' alt="'.$this->escapeHtml($this->getImageLabel()).'" title="'.$this->escapeHtml($this->getImageLabel()).'" '.
                    ' width="56" height="56" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
                ?>
            </div>
            <?php if (count($this->getGalleryImages()) > 0): ?>
                <?php foreach ($this->getGalleryImages() as $_image): ?>
                    <div class="swiper-slide">
                        <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" width="56" height="56" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
        <div class="swiper-button-next-gallery<?php echo $prefixId; ?> swiper-button-next swiper-button-next-gallery"></div>
        <div class="swiper-button-prev-gallery<?php echo $prefixId; ?> swiper-button-prev swiper-button-prev-gallery"></div>
    </div>
<?php endif; ?>
*/ ?>
<div class="product-image-outer">
    <div class="product-image-inner">
          <img class="product-image-zoom"
              src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($_width); ?>"
              data-zoom-image="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>"
              alt="<?php echo $this->escapeHtml($this->getImageLabel()); ?>"
              title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>" />
    </div>
</div>