<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Sarp2
 * @version    2.2.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $profile = $this->getProfile(); ?>
<div class="customer-subscription__view">
    <?php echo $this->getMessagesBlock()->toHtml(); ?>
    <dl class="profile-info">
        <dt><?php echo $this->__('About This Profile:') ?></dt>
        <dd>
            <ul class="profile-info-tabs">
                <li class="current"><strong><?php echo $this->__('Subscription Information'); ?></strong></li>
                <li><a href="<?php echo $this->getUrl('*/*/orders', array('_current' => true)); ?>"><?php echo $this->__('Related Orders'); ?></a></li>
            </ul>
        </dd>
    </dl>
    <div>
        <div class="subscription__view_reference" style="width:50%;display: inline-block;">
            <?php echo $this->getReferenceHtml(); ?>
        </div>
        <div class="subscription__view_purchase" style="width:49%;display: inline-block;">
            <?php echo $this->getPurchaseHtml(); ?>
        </div>
    </div>
    <div>
        <div class="subscription__view_schedule" style="width:50%;display: inline-block;">
            <?php echo $this->getScheduleHtml(); ?>
        </div>
        <div class="subscription__view_payments" style="width:49%;display: inline-block;">
            <?php echo $this->getPaymentsHtml(); ?>
        </div>
    </div>
    <div>
        <div class="subscription__view_billing" style="width:50%;display: inline-block;">
            <?php echo $this->getBillingHtml(); ?>
        </div>
        <div class="subscription__view_shipping" style="width:49%;display: inline-block;">
            <?php echo $this->getShippingHtml(); ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    if ($('main') && $('content_top')) {
        $('main').setStyle({
            paddingTop: $('content_top').getHeight() - parseInt($('page_content').getStyle('padding-top')) + 'px'
        })
    }
    //]]>
</script>

