<?php /* @var $this Mage_Bundle_Block_Catalog_Product_View_Type_Bundle_Option_Checkbox */ ?>
<?php
$_option = $this->getOption();
$_selections = $_option->getSelections();
$_defaults = $this->getSelectionValues();
//$_cHelper = $this->helper('icategory');
$_coreHelper = $this->helper('core');
$_width = 85;
$_height = 85;
$_columnCount=4;
$storeId = Mage::app()->getStore()->getId();
$_optionTitle = $_option->getTitle();
?>
<dd class="bundle-cook-option-item<?php if ($_option->decoratedIsLast){?> last<?php } ?>">
    <div class="input-box">
        <ul class="options-list products-grid">
            <?php $i=0; ?>
            <?php foreach($_selections as $_selection): $i++; ?>
                <?php $_product = $_selection; ?>
                <?php //$_size = $_cHelper->getSize($_selection, $_width, $_height); ?>
                <?php $default = $_defaults[$_selection->getSelectionId()]; ?>
                <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> <?php echo ($i % 2 ? 'odd' : 'even') ?>">
                    <div class="product-image-outer"><div class="product-image-inner">
                            <img src="<?php echo $this->helper('catalog/image')->init($_selection, 'small_image')->resize($_width,$_height); ?>" />
                        </div></div>
                    <h2 class="product-name">
                        <a href="#<?php //echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName(); ?></a>
                    </h2>
                    <div class="price-box">
                            <span class="regular-price">
                                <span class="price"><?php echo $_coreHelper->currency($_product->getPrice()); ?></span>
                            </span>
                    </div>
                    <div class="actions">
                        <div style="display: none;">
                            <input onclick="bundle.changeSelection(this)" class="change-container-classname checkbox bundle-option-<?php echo $_option->getId() ?> <?php if ($_option->getRequired()) echo 'validate-one-required-by-name' ?> button btn-select"
                                   id="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>" type="checkbox" name="bundle_option[<?php echo $_option->getId() ?>][]"<?php if ($this->_isSelected($_selection)) echo ' checked="checked"' ?><?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?> value="<?php echo $_selection->getSelectionId() ?>"
                                />
                        </div>
                        <input type="text" name="bundle_option_qty[<?php
                        echo $_option->getId().'-'.$_selection->getSelectionId() ?>]" value="<?php //echo $default['default_qty'] ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty validated-number input-qty-cook <?php if (!$default['user_defined']) echo ' qty-disabled' ?>" data-checkbox="#bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>"
                            <?php /*onkeyup="bundle.changeOptionQty(this, event)" onblur="bundle.changeOptionQty(this, event)" onchange="bundle.changeOptionQty(this, event);"*/?>
                            <?php
                            if (!$default['user_defined']) echo ' disabled="disabled"' ?> id="bundle-option-<?php
                        echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>-qty-input" />
                    </div>
                    <?php if($_option->getRequired()): ?>
                        <?php echo $this->setValidationContainer('bundle-option-'.$_option->getId().'-'.$_selection->getSelectionId(), 'bundle-option-'.$_option->getId().'-container') ?>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
        <div id="bundle-option-<?php echo $_option->getId() ?>-container"></div>
        <?php //endif; ?>
    </div>
</dd>