<div class="box">
    <div class="box-title">
        <h3><?php echo $this->__('Orders') ?></h3>
    </div>
    <div class="box-content">
        <div id="orders_chart" style="width: 100%; height: 500px;"></div>
    </div>
</div>
<div class="box">
    <div class="box-title">
        <h3><?php echo $this->__('Sales Report') ?></h3>
        <div class="filter-box">
            <ul>
                <li>
                    <div class="field">
                        <div class="input-box">
							<?php $display = Mage::app()->getRequest()->getParam('display', 'total_amount') ?>
                            <select name="sales_display" id="sales_display" class="select-field" onchange="setLocation(this.value);">
                                <option value="<?php echo $this->getDisplayUrl('total_amount') ?>"<?php if ($display == 'today') : ?> selected="selected"<?php endif ?>><?php echo $this->__('-- Total Amount --') ?></option>
                                <option value="<?php echo $this->getDisplayUrl('qty_ordered') ?>"<?php if ($display == 'qty_ordered') : ?> selected="selected"<?php endif ?>><?php echo $this->__('-- Qty Ordered --') ?></option>
                            </select>
                        </div>
                    </div>
                    <div class="field">
                        <div class="input-box">
                            <?php $date = Mage::app()->getRequest()->getParam('date', 'today') ?>
                            <select name="sales_to_date" id="sales_to_date" class="select-field" onchange="setLocation(this.value);">
                                <option value=""><?php echo $this->__('-- None --') ?></option>
                                <option value="<?php echo $this->getOrderedUrl('today') ?>"<?php if ($date == 'today') : ?> selected="selected"<?php endif ?>><?php echo $this->__('-- Today --') ?></option>
                                <optgroup label="<?php echo $this->__('Period') ?>">
                                    <option value="<?php echo $this->getOrderedUrl('yesterday') ?>"<?php if ($date == 'yesterday') : ?> selected="selected"<?php endif ?>><?php echo $this->__('- Yesterday') ?></option>
                                    <option value="<?php echo $this->getOrderedUrl('last_week') ?>"<?php if ($date == 'last_week') : ?> selected="selected"<?php endif ?>><?php echo $this->__('- Last Week') ?></option>
                                    <option value="<?php echo $this->getOrderedUrl('last_month') ?>"<?php if ($date == 'last_month') : ?> selected="selected"<?php endif ?>><?php echo $this->__('- Last Month') ?></option>
                                    <option value="<?php echo $this->getOrderedUrl('last_year') ?>"<?php if ($date == 'last_year') : ?> selected="selected"<?php endif ?>><?php echo $this->__('- Last Year') ?></option>
                                </optgroup>
                                <optgroup label="<?php echo $this->__('To Date') ?>">
                                    <option value="<?php echo $this->getOrderedUrl('current_week') ?>"<?php if ($date == 'current_week') : ?> selected="selected"<?php endif ?>><?php echo $this->__('- Week to Date') ?></option>
                                    <option value="<?php echo $this->getOrderedUrl('current_month') ?>"<?php if ($date == 'current_month') : ?> selected="selected"<?php endif ?>><?php echo $this->__('- Month to Date') ?></option>
                                    <option value="<?php echo $this->getOrderedUrl('current_year') ?>"<?php if ($date == 'current_year') : ?> selected="selected"<?php endif ?>><?php echo $this->__('- Year to Date') ?></option>
                                </optgroup>
                            </select>
                        </div>
                    </div>
                </li>
                <li><span class="filter-or"><?php echo $this->__('Or') ?></span></li>
                <li>
                    <form action="<?php echo $this->getUrl('*/*/*') ?>" method="get">
                    <?php $yesterday = time() - 24 * 60 *60 ?>
					<?php $dateFrom = Mage::app()->getRequest()->getParam('date_from') ?>
					<?php $dateTo = Mage::app()->getRequest()->getParam('date_to') ?>
                    <div class="field">
                        <div class="input-box">
                            <input name="date_from" id="sales_from" value="<?php if ($dateFrom) : ?><?php echo $dateFrom ?><?php endif ?>" class="input-text" type="text" />
                        </div>
                    </div>
                    <div class="field">
                        <div class="input-box">
                            <input name="date_to" id="sales_to" value="<?php if ($dateTo) : ?><?php echo $dateTo ?><?php endif ?>" class="input-text" type="text" />
                        </div>
                    </div>
                    <div class="buttons-set">
                        <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
                    </div>
                    </form>
                </li>
            </ul>
        </div>
    </div>
    <div class="box-content">
        <div id="sales_chart" style="width: 100%; height: 500px;"></div>
        <div class="chart-label"><h3><?php echo $this->getOrderedLabel() ?></h3></div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
function drawChart() {
    var data = google.visualization.arrayToDataTable([
        ['Status', 'Quantity'],
        ['Completed', <?php echo $this->getQtyOrdered('complete') ?>],
        ['Pending', <?php echo $this->getQtyOrdered('pending') ?>],
        ['Processing', <?php echo $this->getQtyOrdered('processing') ?>],
        ['Cancelled', <?php echo $this->getQtyOrdered('cancelled') ?>],
        ['Onhold', <?php echo $this->getQtyOrdered('onhold') ?>],
        ['Review', <?php echo $this->getQtyOrdered('review') ?>]
    ]);

    var options = {
        /*pieHole: 0.4,*/
        legend: {position: 'left'},
        is3D: true
    };

    var pie = new google.visualization.PieChart(document.getElementById('orders_chart'));
    pie.draw(data, options);

	<?php $collection = $this->getOrderedCollection() ?>
	<?php $display = Mage::app()->getRequest()->getParam('display', 'total_amount') ?>
	<?php if ($display == 'qty_ordered') : ?>
    var data = google.visualization.arrayToDataTable([
        ['Date', 'Qty Ordered'],
		<?php $maxQty = 0 ?>
		<?php foreach ($collection as $i) : ?>
			<?php if ($i->getQty() > $maxQty) : ?>
				<?php $maxQty = number_format($i->getQty()) ?>
			<?php endif ?>

			<?php $_qty = number_format($i->getQty()) ?>
			['<?php echo $i->getTimeOrdered() ?>',<?php echo $_qty ?>],
		<?php endforeach ?>
    ]);
    var options = {
		<?php $maxPoint = 10 ?>
		<?php $number = ceil ( count($collection) / (float) $maxPoint ) ?>
		hAxis: {showTextEvery: <?php echo $number ?>},
		vAxis: {title: "<?php echo $this->__('Qty Ordered') ?>", format: '#', minValue: 0, maxValue: <?php echo ceil($maxQty / 10) * 10 ?>},
        pointSize: 8,
        legend: { position: 'right' }
    };
	<?php else : ?>
    var data = google.visualization.arrayToDataTable([
        ['Date', 'Total Amount'],
		<?php $maxTotal = 0 ?>
		<?php foreach ($collection as $i) : ?>
			<?php if ($i->getTotal() > $maxTotal) : ?>
				<?php $maxTotal = number_format($i->getTotal(), 2)?>
			<?php endif ?>

			<?php $_total = number_format($i->getTotal(), 2) ?>
			['<?php echo $i->getTimeOrdered() ?>',<?php echo $_total ?>],
		<?php endforeach ?>
    ]);
    var options = {
		<?php $maxPoint = 10 ?>
		<?php $number = ceil ( count($collection) / (float) $maxPoint ) ?>
		hAxis: {showTextEvery: <?php echo $number ?>},
		vAxis: {title: "<?php echo $this->__('Total Amount') ?>", format:'currency', minValue: 0, maxValue: <?php echo ceil($maxTotal / 10) * 10 ?>},
        pointSize: 8,
        legend: { position: 'right' }
    };
	<?php endif ?>

    var line = new google.visualization.LineChart(document.getElementById('sales_chart'));
    line.draw(data, options);
}

/* Calendar */
Calendar.setup({
    inputField : 'sales_from',
    ifFormat : '%d/%m/%Y',
    align : 'Bl',
    singleClick : true,
    /*
    onSelect: function(dateText, selectedDate) {
        var pattern = /(\d{2})\/(\d{2})\/(\d{4})/;

        var from = new Date(selectedDate.replace(pattern,'$3-$2-$1'));
        var to = new Date($('sales_to').value.replace(pattern,'$3-$2-$1'));
        if (from >= to) {
            alert('<?php echo $this->__('From date should be less than to date') ?>');
            return false;
        }
        return selectedDate;
    },
    */
});

Calendar.setup({
    inputField : 'sales_to',
    ifFormat : '%d/%m/%Y',
    align : 'Bl',
    singleClick : true,
    /*
    onSelect: function(dateText, selectedDate) {
        var pattern = /(\d{2})\/(\d{2})\/(\d{4})/;

        var from = new Date($('sales_from').value.replace(pattern,'$3-$2-$1'));
        var to = new Date(selectedDate.replace(pattern,'$3-$2-$1'));
        if (from >= to) {
            alert('<?php echo $this->__('To date should be greater than from date') ?>');
            return false;
        }
        return selectedDate;
    },
    */
});
//]]>
</script>