<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="product-view cook-view-details">
    <div class="product-essential">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
            <div class="product-shop">
                <div class="product-name">
                    <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                </div>

                <div class="product-description">
                    <div class="pd-text">
                        <?php if ($s = $_product->getData('description')):?>
                            <?php echo $_helper->productAttribute($_product, $s, 'description') ?>
                        <?php endif; ?>
                    </div>
                    <div class="pd-image">
                        <?php echo $this->getChildHtml('media_mobile') ?>
                    </div>
                </div>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                    <div class="clearer"></div>
                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                <?php endif;?>

                <div class="add-to-box">
                    <?php echo $this->getChildHtml('addto') ?>
                    <?php //echo $this->getChildHtml('addtocart') ?>
                    <?php if($_product->isSaleable()): ?>
                        <div class="add-to-cart">
                            <?php if(!$_product->isGrouped()): ?>
                                <input type="hidden" name="qty" value="<?php echo $this->getProductDefaultQty() * 1 ?>" />
                            <?php endif; ?>
                            <button type="button" title="<?php echo $this->__('Add to cart'); ?> ?>" id="product-addtocart-button" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $this->__('Add to cart'); ?></span></span></button>
                        </div>
                    <?php endif; ?>
                </div>
                <div style="display: none">
                    <?php echo $this->getChildHtml('product_type_data') ?>
                    <?php echo $this->getTierPriceHtml() ?>
                </div>
                <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php echo $this->getChildHtml('alert_urls') ?>
                <?php echo $this->getChildHtml('extrahint') ?>
                <?php echo $this->getChildHtml('other');?>

            </div>
        </form>
        <script type="text/javascript">
            //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                        form.action = url;
                    }
                    var e = null;

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }

                    <?php if (Mage::helper('core')->isModuleEnabled('VS_Ajax') and Mage::getStoreConfig('ajax/general/enabledpro')) : ?>
                    if (!url) {
                        url = jQuery('#product_addtocart_form').attr('action');
                    }
                    url = url.replace("checkout/cart","ajax/index"); // New Code
                    var data = jQuery('#product_addtocart_form').serialize();
                    data += '&isAjax=1';
                    jQuery('#ajax_loader').show();
                    try {
                        jQuery.ajax( {
                            url : url,
                            dataType : 'json',
                            type : 'post',
                            data : data,
                            success : function(data) {
                                jQuery('#ajax_loader').hide();
                                if(data.status == 'ERROR'){
                                    alert(data.message);
                                }else{
                                    var csSelector = "<?php echo Mage::getStoreConfig('ajax/general/cs_selector') ?>";
                                    if(jQuery(csSelector)){
                                        jQuery(csSelector).replaceWith(data.sidebar);

                                        var openTO;
                                        var menu = jQuery('#header_cart_content');
                                        jQuery("#header_cart_container").hover(function() {
                                            if (jQuery(this).hasClass('open')) {
                                                menu.stop(true, true).delay(200).fadeIn(600, "easeOutCubic");
                                            } else {
                                                clearTimeout(openTO);
                                                openTO = setTimeout(function() {
                                                    jQuery(this).addClass('open');

                                                }, 200);
                                                menu.stop(true, true).delay(200).fadeIn(600, "easeOutCubic");
                                            }
                                        }, function() {
                                            clearTimeout(openTO);
                                            menu.stop(true, true).delay(200).fadeOut(200, "easeInCubic");
                                            jQuery(this).removeClass('open');
                                        });
                                    }

                                    var tlSelector = "<?php echo Mage::getStoreConfig('ajax/general/tl_selector') ?>";
                                    if(jQuery(tlSelector)){
                                        jQuery(tlSelector).replaceWith(data.toplink);
                                    }
                                }
                                if (button && button != 'undefined') {
                                    button.disabled = false;
                                }
                            }
                        });
                    } catch (e) {
                    }
                    <?php else : ?>
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    <?php endif ?>

                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
            jQuery(document).ready(function($) {
                //input-qty-cook bundle.changeSelection(this)
                $(document).on('change','.input-qty-cook',function(event) {
                    idCheckbox = $(this).attr('data-checkbox');
                    valueInput = $(this).val();
                    flagTrue = false;
                    if($.isNumeric(valueInput)) {
                        valueInput = parseInt(valueInput);
                        if(valueInput > 0) {
                            $(idCheckbox).prop('checked',true);
                            flagTrue = true;
                            bundle.changeSelection($(idCheckbox)[0]);
                        }
                    }
                    if(!flagTrue) {
                        $(idCheckbox).prop('checked',false);
                        bundle.changeSelection($(idCheckbox)[0]);
                    }
                });
            });
            //]]>
        </script>
    </div>
</div>
